### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by marcelomanzo** [ronny-rentner/UltraDict#10]
Cannot re-start my app, even after restart the computer.

C:\Users\marce\PycharmProjects\srsapp\venv310\Scripts\python.exe C:/Users/marce/PycharmProjects/srsapp/launcher.py --enable_file_cache True
Traceback (most recent call last):
  File "C:\Users\marce\PycharmProjects\srsapp\launcher.py", line 7, in <module>
    import globalVariables
  File "C:\Users\marce\PycharmProjects\srsapp\globalVariables.py", line 574, in <module>
    config = UltraDict(name='config1', size=500000) 
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\UltraDict\UltraDict.py", line 288, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\marce\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py", line 1092, in __init__
    self.update(kwargs)
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\UltraDict\UltraDict.py", line 498, in update
    self[k] = v
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\UltraDict\UltraDict.py", line 514, in __setitem__
    self.apply_update()
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\UltraDict\UltraDict.py", line 464, in apply_update
    self.load(force=True)
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\UltraDict\UltraDict.py", line 398, in load
    full_dump_memory = self.get_memory(create=False, name=name)
  File "C:\Users\marce\PycharmProjects\srsapp\venv310\lib\site-packages\UltraDict\UltraDict.py", line 329, in get_memory
    raise Exception("Could not get memory: ", name)
Exception: ('Could not get memory: ', 'wnsm_0ce9a65a')
Exception ignored in: <function SharedMemory.__del__ at 0x000001F84F477880>
Traceback (most recent call last):
  File "C:\Users\marce\AppData\Local\Programs\Python\Python310\lib\multiprocessing\shared_memory.py", line 184, in __del__
    self.close()
  File "C:\Users\marce\AppData\Local\Programs\Python\Python310\lib\multiprocessing\shared_memory.py", line 227, in close
    self._mmap.close()
BufferError: cannot close exported pointers exist

**Comment by ronny-rentner** [comment]
It's looks like you're trying to attach to an existing UltraDict and during this process it tries to import a full dump from the memory 'wnsm_0ce9a65a' but that memory does not exist anymore. On Windows, if the process goes away that has created the full dump memory, Windows cleans up the memory.

Thus, your UltraDict is possibility in an inconsistent state. It might help to re-create it.

**Comment by hemakumar01** [comment]
Hi ronny-rentner................is there a way to clear the UltraDict instance after we are done with it.......to avoid issues like too many UltraDict instances or file handlers................. currently im facing the issue.

**Comment by ronny-rentner** [comment]
@hemakumar01 Hey, well, the latest changes in the dev branch should handle the cleanup. At least in the unit tests, it works properly where it failed before, but I have only tested file handles on Linux because I don't know how to analyse open file handles on Windows. Of course it also depends on the Python program not to keep any references on the UltraDicts because otherwise they will not be garbage collected.

You can try to run 
```
>>> # Close connection to shared memory; will return the data as a dict
>>> ultra.close()

>>> # Unlink all shared memory, it will not be visible to new processes afterwards
>>> ultra.unlink()
```
manually if you want but that should actually be done automatically.

**Comment by ronny-rentner** [comment]
I am closing this issue due to inactivity. Feel free to reopen if the problem persists.
