### ISSUE TITLE
Extremely slow initialization from existing dict

### ISSUE THREAD

**Issue by kc9jud** [ronny-rentner/UltraDict#15]
Initializing from a (large) existing dict is slow -- it seems to be serializing every key-value pair as an update:

```
Traceback (most recent call last):
  File "/global/homes/p/pfasano/group_stats_dict.py", line 327, in <module>
    group_dict = read_groups(partitions, sp_bin)
  File "/global/homes/p/pfasano/group_stats_dict.py", line 206, in read_groups
    return UltraDict(group_dict, auto_unlink=True)
  File "/global/homes/p/pfasano/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/UltraDict/UltraDict.py", line 301, in __init__
    super().__init__(*args, **kwargs)
  File "/global/common/software/nersc/pm-2022q2/sw/python/3.9-anaconda-2021.11/lib/python3.9/collections/__init__.py", line 1046, in __init__
    self.update(dict)
  File "/global/homes/p/pfasano/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/UltraDict/UltraDict.py", line 541, in update
    self[k] = v
  File "/global/homes/p/pfasano/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/UltraDict/UltraDict.py", line 568, in __setitem__
    self.append_update(key, item)
  File "/global/homes/p/pfasano/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/UltraDict/UltraDict.py", line 482, in append_update
    self.dump()
  File "/global/homes/p/pfasano/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/UltraDict/UltraDict.py", line 374, in dump
    marshalled = self.serializer.dumps(self.data)
```

It seems like somehow `super().__init__` is calling `collections.UserDict.__init__`, which in turn calls `UltraDict.__setitem__`.

I guess I don't quite understand yet how UltraDict works, but why does every key need to be serialized as an update to an empty dict?

**Comment by kc9jud** [comment]
(Just to clarify, when I say "large", I mean very large -- 3GiB to 60 GiB. Hence why I don't want to copy it between processes...)

**Comment by ronny-rentner** [comment]
Well, UltraDict creates an internal copy of the dict contents for each process. This internal copy is stored in a normal Python dict which is accessible via the data attribute. This allows for fast reads from the internal copy.

The idea of UltraDict is to not have a server or management process but if you want only one copy, you'll need a server or management process. You could maybe use Redis or memcached?

**Comment by ronny-rentner** [comment]
PS: You can check out this issue regarding performance of initialization and how to get it fast: https://github.com/ronny-rentner/UltraDict/issues/13

**Comment by ronny-rentner** [comment]
PPS: I guess you could also just read in your data once in a central main process and then fork child processes. It should not create a copy of your data for the child processes as long as you don't do any writes in the data after forking.
