### ISSUE TITLE
Crashes under high load

### ISSUE THREAD

**Issue by rojamit** [ronny-rentner/UltraDict#7]
master process is writing to 1 nested dict1 (recurse=1) shared between 20-40 processes,  total dict1 size ~1500 keys with nested dict (as value, small)

processes created via multiprocessing.Process, and writing to other shared dict - dict2[process_id] once per second, dict2 size - same, but *num_processes 

main process analyzing statistics from dict2: for process_id in dict2: dict2[process_id]: ...
and write changes to shared dict1 once per second: for change in changes: dict1['nested'][change] = {'time': 123, 'blah': '123'}

crashing appears if changes size is 300-2000 in 1 second, and read lookups is HUGE (>100k/sec) but i tried to cache it once per second to local dict using deepcopy and this doesnt help...
total memory usage not exceed 2-4GB i think (free ram is about 60GB), CPU usage up to 100%

dict1 size in bytes determined on local dict with same structure is less than 150kb

i tried:
1. copy.deepcopy(dict1) once per second to create a local copy in processes for cached lookups - doesn't help
2. shared_lock
3. with dict1.lock/etc
4. increasing buffer to huge values, increasing full dump size/etc

and nothing helps... on low speeds (or no/small changes from master to dict1) all is working, or using multiprocessing.manager().dict all is working too, but slow

Examples of exceptions:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
	self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
	self._target(*self._args, **self._kwargs)
  File "zvshield.py", line 793, in zvshield.accept_connections
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 585, in __contains__
	self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 511, in apply_update
	assert bytes(self.buffer.buf[pos:pos+1]) == b'\x00'
AssertionError
```
```

File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 248, in __init__
	self.buffer = self.get_memory(create=True, name=self.name + '_memory', size=buffer_size)
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 347, in get_memory
	full_dump = self.serializer.loads(bytes(buf[pos:pos+length]))
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 304, in __init__
	self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 520, in apply_update
	memory = multiprocessing.shared_memory.SharedMemory(name=name)
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 114, in __init__
	mode, key, value = self.serializer.loads(bytes(self.buffer.buf[pos:pos+length]))
	self._mmap = mmap.mmap(self._fd, size)
OSError: [Errno 12] Cannot allocate memory

EOFError: Ran out of input
Exception ignored in: <function SharedMemory.__del__ at 0x7fb80639e820>
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 184, in __del__
	self.close()
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 227, in close
Exception ignored in: <function SharedMemory.__del__ at 0x7fb80639e820>
	self._mmap.close()
Traceback (most recent call last):
BufferError: cannot close exported pointers exist
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 184, in __del__
	self.close()
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 227, in close
	self._mmap.close()
BufferError: cannot close exported pointers exist
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 184, in __del__
	self.close()
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 227, in close
	self._mmap.close()
BufferError: cannot close exported pointers exist
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
	self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
	self._target(*self._args, **self._kwargs)
  File "zvshield.py", line 793, in zvshield.accept_connections
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 585, in __contains__
	self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 500, in apply_update
	self.load(force=True)
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 450, in load
	full_dump = self.serializer.loads(bytes(buf[pos:pos+length]))
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 304, in __init__
	self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 520, in apply_update
	mode, key, value = self.serializer.loads(bytes(self.buffer.buf[pos:pos+length]))
EOFError: Ran out of input
Exception ignored in: <function SharedMemory.__del__ at 0x7fc48f4d4820>
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 184, in __del__
	self.close()
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 227, in close
	self._mmap.close()
BufferError: cannot close exported pointers exist
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
	self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
	self._target(*self._args, **self._kwargs)
  File "zvshield.py", line 793, in zvshield.accept_connections
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 585, in __contains__
	self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 500, in apply_update
	self.load(force=True)
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 450, in load
	full_dump = self.serializer.loads(bytes(buf[pos:pos+length]))
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 304, in __init__
	self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 520, in apply_update
	mode, key, value = self.serializer.loads(bytes(self.buffer.buf[pos:pos+length]))
EOFError: Ran out of input
```
```
Exception ignored in: <function SharedMemory.__del__ at 0x7fc48f4d4820>
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 184, in __del__
	self.close()
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 227, in close
	self._mmap.close()
BufferError: cannot close exported pointers exist

```

**Comment by rojamit** [comment]
interesting that after exceptions like above python starts to crashing in other parts of code:
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f9f9ce0d370>
transport: <_SelectorSocketTransport fd=172 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
MemoryError
Fatal read error on socket transport

but free memory is HUGE and ram usage is small

**Comment by rojamit** [comment]
Traceback (most recent call last):
  File "zvshield.py", line 598, in shared_dict_updater
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 557, in __setitem__
    self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 500, in apply_update
    self.load(force=True)
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 450, in load
    full_dump = self.serializer.loads(bytes(buf[pos:pos+length]))
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by rojamit** [comment]
reducing "changes" updates from 
"for change in changes: dict1['nested']['change'] = change" 
to
 "dict['nested'] = changes" 
 
 helping... not a fix but workaround

**Comment by ronny-rentner** [comment]
@rojamit Many thanks for your report. I'll look into it and try to analyze what's going on. In the meantime, feel free to test the dev branch. It possibly contains fixes for some of the errors you have seen.

There's also a new example `examples/mccoydj1.py` (from issue #6 ) in the dev branch where 2 processes write with maximum speed and one process reads with maximum speed. The fixes in the dev branch are mainly to stabilize this.

**Comment by mccoydj1** [comment]
ooooo.... my terribly cruel use case earned itself its own example file! Sorry for causing so much pain... thanks for your help improving this library :)

**Comment by ronny-rentner** [comment]
@rojamit Regardig your points:

1. There already is `dict1.data` which is a local copy and you can use it to access the dict cached data. You could then run `dict1.apply_update()` manually to update the local copy once a sec or so.
2. If you fork your processes from a parent process, you can use the faster RLock with shared_lock=False.
3. Using the lock should help, but it depends on your situation. Reads are not protected by locks for performance. The dev branch contains some code to better protect reads. 
4. You need to find the right balance for the buffer sizes. If your total data is like 150k, I wouldn't make the buffer much bigger.

Please let me know if the dev branch improves your situation.

**Comment by rojamit** [comment]
@ronny-rentner thanks, i'll test dev branch today

my current buffer_size=500000

in my case (for now) there is 1 write/sec from master process, same for each child process, but child processes may read dict at 100k/s speed or even more

i have structure like dict[process_id] for each child process, do i still need locks?

**Comment by rojamit** [comment]
@ronny-rentner dev branch is much more stable. but... after about 12 hours, master has crashed:
future: <Task finished name='Task-1' coro=<<coroutine without __name__>()> exception=OSError(12, 'Cannot allocate memory')>
Traceback (most recent call last):
  File "zvshield.py", line 515, in main
  File "zvshield.py", line 410, in zvshield.analyze_netstat
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 264, in _reconstruct
    y = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 369, in __init__
    self.lock = multiprocessing.RLock()
  File "/usr/lib/python3.9/multiprocessing/context.py", line 73, in RLock
    return RLock(ctx=self.get_context())
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 187, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
  File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 12] Cannot allocate memory
Exception ignored in: <function SharedMemory.__del__ at 0x7f01051974c0>
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 184, in __del__
    self.close()
  File "/usr/lib/python3.9/multiprocessing/shared_memory.py", line 227, in close
    self._mmap.close()
BufferError: cannot close exported pointers exist

**Comment by ronny-rentner** [comment]
@rojamit Thanks for the update. 

Regarding your question:
> i have structure like dict[process_id] for each child process, do i still need locks?

No, in this case you don't need additional locks. UltraDict will use locks internally to protect writes. Though, you have to use `shared_lock=true` if you spawn the processes. If you fork them all from the same master process, that is not necessary.

Regarding the remaining exception(s):
Interesting. Can you check how much shared memory is left if you get such an exception? The error does not seem to happen directly in UltraDict but when Python tried to initialize an RLock. 
`File "/usr/lib/python3.9/multiprocessing/synchronize.py", line 57, in init
sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 12] Cannot allocate memory`
Though, of course it could be caused by UltraDict not doing clean up correctly.

Over those 12 hours, are you using the same UltraDicts or are you creating new ones?
UltraDict tries to initialize its lock only when a new instance is created.
`File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 369, in init
self.lock = multiprocessing.RLock()`
Are you maybe (accidentally?) keeping around lots of UltraDict instances until all memory is gone?

**Comment by rojamit** [comment]
@ronny-rentner using dev branch, app is running fine for 2 days now (no restarts), definitely dev is much more stable: no errors from UltraDict during this period.

I'm creating these dicts once (at startup):
`	HOST_SETTINGS = UltraDict({}, buffer_size=1000000, recurse=True)
	WORKERS = UltraDict({}, buffer_size=1000000)
	ADDR_INFO = UltraDict({
		'banned': {},
		'checked': UltraDict({}, buffer_size=1000000)
	}, buffer_size=1000000)
	EVENT_BUS = UltraDict({
		'events': {},
		'new_ssl': {}
	}, buffer_size=1000000, recurse=True)`

**Comment by rojamit** [comment]
@ronny-rentner yay just told all is ok and now after load spike app crashed again

40 processes, 200+k/s readings like "if x in dict1.data['key']"
dict1.data['key'] is a nested dict

crashed with KeyError: 'key', and then looks like ultradict is disconnected from process where error appears

**Comment by ronny-rentner** [comment]
@rojamit That's interesting because `ADDR_INFO.data` is an original Python dict. If I understand it correctly, KeyError simply means that 'banned' does not exist in the dict. If you access `ADDR_INFO['banned']`, does it work? If you can catch the error, can you run `ADDR_INFO.print_status()` so we get some more debug info?

**Comment by rojamit** [comment]
@ronny-rentner i'll try print_status, but 'banned' is always-existing key... processes are crashing randomly on high load (not all in one time!), 'banned' is updating from master process using ADDR_INFO[banned] = x, other processes only reading, and gets updates in another asyncio coroutine using ADDR_INFO.apply_update() (of course in its process)

if this KeyError occurs in process, he never recovers, in simple words it looks like that process is disconnected from UltraDict, i dont know how exactly UltraDict works in details, but can 'banned' disappear from .data while UltraDict is updating (or doing something else)?

**Comment by rojamit** [comment]
@ronny-rentner also using recurse=True increased errors alot

**Comment by ronny-rentner** [comment]
@rojamit
> i dont know how exactly UltraDict works in details, but can 'banned' disappear from .data while UltraDict is updating (or doing something else)?

UltraDict works with a stream of updates. This includes the possibility of sending a *delete* message in the update stream. If you run `del ADDR_INFO['banned']` in one of the processes, it will try to propagate this update. This is eventually just one byte in the update stream that tells UltraDict to either delete or update the key. 

You could try to add some debug prints in the `__delitem__()` method to find out if really a delete message is being received. https://github.com/ronny-rentner/UltraDict/blob/42066b997b99d8882c27ef7bb8bf722ca648ac8a/UltraDict.py#L545

During my tests I had lowered the buffer_size to a really tiny value (like 100 or 1000 bytes). This has triggered the error much faster. Is this also the case with your program? It might make it easier to get a stack trace.

**Comment by ronny-rentner** [comment]
@rojamit I've found an error which only appears with full dumps and recurse=True which is most likely the cause for your `OSError: [Errno 12] Cannot allocate memory` and it might be the cause for other errors. It seems some file pointers are left behind and never closed and at some point you run out of memory or have too many files open. I'll let you know once I have a fix.

**Comment by rojamit** [comment]
@ronny-rentner yes, looks like error only appears with recurse=True (with dev branch)
'banned' key is always-existing key as i mentioned, it never gets deleted.
In my case some processes crashes but others continue work, but when key is deleted i think its not possible way

Looks like dev is stable without recurse=True and with updating method i mentioned (for large updates)

**Comment by rojamit** [comment]
@ronny-rentner some errors on high load today

```
ERROR:root:Exception 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 649, in apply_update
    assert bytes(self.buffer.buf[pos:pos+1]) == b'\xFF'
AssertionError

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "zvshield.py", line 247, in zvshield.HttpProtocol.data_received
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 753, in __contains__
    self.apply_update()
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 692, in apply_update
    raise e
  File "/usr/local/lib/python3.9/dist-packages/UltraDict/UltraDict.py", line 649, in apply_update
    assert bytes(self.buffer.buf[pos:pos+1]) == b'\xFF'
AssertionError

WARNING:root:Full dumps too fast full_dump_counter=20 full_dump_counter_remote=21. Consider increasing buffer_size.
```

**Comment by ronny-rentner** [comment]
@rojamit Unfortunately the line numbers are not matching the dev branch exactly anymore. It's a bit strange because I had added code to actually use a lock as a last resort to recover from such errors. You can find it here: https://github.com/ronny-rentner/UltraDict/blob/dev/UltraDict.py#L691 Either there are more edge cases that I didn't find yet or the locking is not working correctly on your computer or your're running older code that did not have the lock as a fallback.

The root cause, at least as far as I understand it, is too small buffers. I think the following is happening:
* You have 2 processes.
* Process 1 is writing changes to the shared memory dict.
* Process 2 is reading changes from the shared memory dict.

Imagine Process 2 is in the middle of processing an streaming update from the stream buffer but your operating system then pauses this process and gives another process some CPU time.

While Process 2 is paused, Process 1 continues to write updates to the stream. It has so many updates that it needs to create a full dump and reset the stream. And then it will continue to write more updates to the stream until it reaches the position in the stream where Process 2 currently is (but paused). Process 2 is still in the middle of processing the old update from the stream. Process 1 is lapping Process 2 and thus Process 2 is not able to finish processing the streaming updates.


Which buffer size are you using? Does it help to increase the buffer size? Ideally increase it until you don't get warnings anymore about too fast full dumps.

**Comment by rojamit** [comment]
@ronny-rentner my buffer size is `buffer_size=1000000` (as you can see in my past messages)

yes, i think the same about r/w issue, i'll update UltraDict again and check if error still occurs (previously updated from dev about week ago)

**Comment by rojamit** [comment]
@ronny-rentner looks like json.dumps doesnt work with UltraDict(recurse=True), even when accessing it through .data

from nested dict like {k:{k:v}} json.dumps returns only {k: {}} (empty dict), strange

**Comment by rojamit** [comment]
@ronny-rentner i think dev is working stable for now, without recurse=True. No errors during week at all

**Comment by ronny-rentner** [comment]
@rojamit Thanks for the feedback. I'm glad it works in this mode. I'm still working on improvements and cleanup for the recursive mode.

**Comment by ronny-rentner** [comment]
@rojamit There are some new improvements in the dev branch that are supposed to help on the recurse mode. I'm not sure if I should actually keep it or remove this feature as it adds quite some complexity.

Regarding json: Yes, I've noticed there are different json packages and `jsons` seems to do what we need.

```
>>> ultra
{'nested': {1: 1}}
>>> json.dumps(ultra)
'{}'
>>> jsons.dumps(ultra)
'{"nested": {"1": 1}}'
```

**Comment by rojamit** [comment]
@ronny-rentner looks like i missed something, or performance on latest dev branch decreased

for now i have large dict (1k-50k keys or more) with statistics per IP to hostname, for example:
{ 1.1.1.1: {hostname1: 11, hostname2: 37}, ... }

40 worker-processses counting requests and store stats in local dict

i need to summarize stats from all processes
previously i used method like:
`shared_dict_workers[worker_id] = stats` in worker,
 and then loop over shared_dict_workers in master process 
 
 but it has poor performance because of increased complexity O(workers_count=40), same about ram usage
 
 so i tried to create shared_dict_stats which gets updated directly from workers with lock from local worker_stats
 but ultradict is huge bottleneck here, and i cant even use dict.data & dict.apply_update() because it doesnt work 
 dirty sketch:
 `import UltraDict, multiprocessing, time

stats_total = UltraDict.UltraDict(buffer_size=1_000_000, recurse=True)

def worker(pid):
    worker_stats = {                                                                               # worker_stats isnt static irl
        f'{i}.{i}.{i}.{i}': dict( (f'hostname-{x}', x) for x in range(10) ) for i in range(3000) } # 3000 = keys, 10 = hostnames 
    while 1:
        with stats_total.lock:
            for addr in worker_stats:
                if addr not in stats_total.data:
                    stats_total[addr] = worker_stats[addr]
                for hostname in worker_stats[addr]:
                    if hostname not in stats_total.data[addr]:
                        stats_total[addr][hostname] = worker_stats[addr][hostname]
                    stats_total[addr][hostname] += 1 # actually it must be 'worker_stats[addr][hostname]', not 1
        #print('updated from worker', pid)
        time.sleep(0.001)

for pid in range(10): # processes count
    process = multiprocessing.Process(target=worker, args=(pid,))
    process.daemon = True
    process.start()
time.sleep(2)

last = 0
while 1:
    print('updates/sec:', stats_total['1.1.1.1']['hostname-1'] - last,
          'total:', stats_total['1.1.1.1']['hostname-1'])
    last = stats_total['1.1.1.1']['hostname-1']
    time.sleep(1)
`
i need to summarize these stats once per second, but this sketch have lower rate (because of performance)

**Comment by rojamit** [comment]
this works alot faster (mostly because of recurse=False?)
```
import UltraDict, multiprocessing, time

stats_total = UltraDict.UltraDict(buffer_size=1_000_000, recurse=False, data = {                                                                               # worker_stats isnt static irl
    f'{i}.{i}.{i}.{i}': dict( (f'hostname-{x}', x) for x in range(10) ) for i in range(3000)})

def worker(pid):
    while 1:
        with stats_total.lock:
            new = stats_total['data'].copy()
            for addr in new:
                for hostname in new[addr]:
                    new[addr][hostname] += 1  # must be 'worker_stats[addr][hostname]', not 1
            stats_total['data'] = new
        #print('updated from worker', pid)
        time.sleep(0.01)

for pid in range(10): # processes count
    process = multiprocessing.Process(target=worker, args=(pid,))
    process.daemon = True
    process.start()
time.sleep(2)

last = 0
while 1:
    print('updates/sec:', stats_total['data']['1.1.1.1']['hostname-1'] - last,
          'total:', stats_total['data']['1.1.1.1']['hostname-1'])
    last = stats_total['data']['1.1.1.1']['hostname-1']
    time.sleep(1)
```

**Comment by rojamit** [comment]
my super-naive realization of something like shared dict shows that looks like actual problem is not with UltraDict, but with slow shared memory io itself:

`import multiprocessing, time, ctypes
lock = multiprocessing.RLock()

shared_string = multiprocessing.RawArray(ctypes.c_char, b'\x00'* 500000)
shared_string.value = str({                                                                              
    f'{i}.{i}.{i}.{i}': dict( (f'hostname-{x}', x) for x in range(2) ) for i in range(5000)}).encode()

def worker(pid,shared_str):
    while 1:
        t1 = time.time()
        with lock:
            new = eval(shared_str.value)
            for addr in new:
                for hostname in new[addr]:
                    new[addr][hostname] += 1
            shared_str.value = str(new).encode()
        t2 = time.time()
        print('updated from worker', pid, 'took', float(t2-t1), new['1.1.1.1']['hostname-1'])
#        time.sleep(0.5)

for pid in range(40): # processes count
    process = multiprocessing.Process(target=worker, args=(pid,shared_string))
    process.daemon = True
    process.start()
time.sleep(2)

last = 0
while 1:
    stats = eval(shared_string.value)
    print(stats['1.1.1.1'])
    print('updates/sec:', stats['1.1.1.1']['hostname-1'] - last,
          'total:', stats['1.1.1.1']['hostname-1'])
    last = stats['1.1.1.1']['hostname-1']
    time.sleep(1)`
 
 output:
 updates/sec: 24 total: 115
updated from worker 35 took 1.7005925178527832 117
updated from worker 36 took 1.6961350440979004 118
updated from worker 37 took 1.6979949474334717 119
updated from worker 38 took 1.6976847648620605 120
updated from worker 39 took 1.6979420185089111 121
updated from worker 0 took 1.697028636932373 122
updated from worker 1 took 1.695997714996338 123

**Comment by rojamit** [comment]
for now my best is:
(not related to ultradict, but for performance comparison) 

`import multiprocessing, time
from multiprocessing import RLock
import msgpack
import mmap
lock = RLock()

_data = msgpack.packb({                                                                              
    f'{i}.{i}.{i}.{i}': dict( (f'hostname-{x}', x) for x in range(1) ) for i in range(50000)})
shared_string = mmap.mmap(-1, len(_data)+100000)
shared_cursor = multiprocessing.RawValue('i', 0)
shared_string.write(_data)
shared_cursor.value = shared_string.tell()

def worker(pid,shared_str):
    while 1:
        t1 = time.time() 
        with lock:
            msg_len = shared_cursor.value
            shared_str.seek(0)
            _data = shared_str.read(msg_len)
            try:
                new = msgpack.unpackb(_data, max_map_len=50000)
            except Exception as error:
                assert msg_len == len(_data)
                print(error, 'msg len', msg_len, [_data])
            else:
                for addr in new:
                    for hostname in new[addr]:
                        new[addr][hostname] += 1
                shared_str.seek(0)
                packed = msgpack.packb(new)
                wrote = shared_str.write(packed)
                #print('wrote', wrote, 'cursor', shared_str.tell(), 'packed', len(packed))
                shared_cursor.value = shared_str.tell()
        t2 = time.time()
        print('updated from worker', pid, 'took', float(t2-t1), new['1.1.1.1']['hostname-0'])
        time.sleep(0.5)

for pid in range(40): # processes count
    process = multiprocessing.Process(target=worker, args=(pid,shared_string))
    process.daemon = True
    process.start()
time.sleep(2)

last = 0
while 1:
    '''stats = eval(shared_string.value)
    print(stats['1.1.1.1'])
    print('updates/sec:', stats['1.1.1.1']['hostname-1'] - last,
          'total:', stats['1.1.1.1']['hostname-1'])
    last = stats['1.1.1.1']['hostname-1']'''
    time.sleep(1)
  `
  
 this code solves my task (because runs faster) - 50k dict got updated from 40 processes within a second with 2% total CPU usage, code itself took only 50ms per process, but with lock its about 1sec... how to do it without locking and separate dicts/etc?

**Comment by ronny-rentner** [comment]
Thanks for sharing the code. If I may, I'll use it as a future example and I'll try to make UltraDict fast for this use case.

**Comment by rojamit** [comment]
@ronny-rentner Yes, of course you can
However, I was not able to achieve acceptable performance when using RLock's on the number of processes = 40 updating a large dictionary more than once a second (then working directly with mmap/shared memory without UltraDict)

Therefore, I abandoned the locks, instead I synchronize updates from main process, sending a signal to the child processes (after which the process writes updated dictionary to mmap), then, after the update is completed, the child process sends a signal to the main process, and everything repeats with the remaining processes (locks are not needed here because at one time only one process works with mmap due to synchronization from the main process)
(main process itself does not update the dictionary, but tell childs to update it one by one and then fetchs result from mmap)

With this approach, it is possible to update a dictionary of 50 thousand keys in size from 40 processes in 300 milliseconds of time in the main process, spending less than 5% of the total CPU time (on my configuration)

(300ms because it takes 7.5ms for a child process to update on such a dictionary size, and the main process just waits for the completion signal to pass the turn to the next child process)

those results achieved using marshal and mmap, python built-in packages

**Comment by ronny-rentner** [comment]
@rojamit 

I've taken your explanations and came up with the following approach:

```python
import multiprocessing, threading, time
import sys; sys.path.insert(0, '..')
from UltraDict import UltraDict
from collections import defaultdict

number_of_items = 50_000
update_interval = number_of_items * 10
number_of_processes = 4

def worker(pid, ultra):

    update_signal = threading.Event()
    updater_data = {}
    def updater():
        while update_signal.wait():
            with ultra.lock:
                ultra.apply_update()
                for k, v in updater_data.items():
                        ultra.data[k] += v
                ultra.dump()
            update_signal.clear()

            # only print for first process
            #if pid == 0: print(f'{pid} : update done')

    update_thread = threading.Thread(target=updater)
    update_thread.start()

    data = defaultdict(int)

    updated = 0
    t1 = time.perf_counter()
    while True:

        ##
        # Do some work, count something fast
        ##

        for i in range(number_of_items):

            data[i] += 1

            # Count number of updates to local dict
            updated += 1

        # If we have more than `update_interval` updates, then we send a signal to the
        # update thread to dump all the changes to the shared memory. We could also do
        # this time based every N seconds or based on another signal from the parent process.
        if updated > update_interval:
            t2 = time.perf_counter()
            #print(pid, 'inc:', (t2 - t1)*1000)

            # only print for first process
            #if pid == 0: print(pid, ':', int((updated / (t2 - t1))/1000), 'kupds/s', 'len: ', len(data))

            if update_signal.is_set():
                # The updater is not done yet, we cannot do another update, let's try next time
                # TODO: There's a risk we never get the chance to apply our updates
                continue

            # The updater thread will work on this copy of our data
            updater_data = data.copy()
            data = defaultdict(int)
            updated = 0

            update_signal.set()

            t1 = time.perf_counter()



t0 = time.perf_counter()

# Use static full dump memory for more write performance,
# 50 bytes per item (which is an int)
ultra = UltraDict(full_dump_size=number_of_items * 50)

for pid in range(number_of_processes):

    # This will make sure the value is `0` for non-existing keys
    ultra.data = defaultdict(int)

    process = multiprocessing.Process(target=worker, args=(pid, ultra), daemon=True)
    process.start()
        # ultra.data is direct access to underlying local dict

last = 0
while True:

    # print stats roughly every second
    time.sleep(1)

    stats = ultra
    print(stats[0])
    t1 = time.perf_counter()
    delta = stats[0] - last
    t_delta = t1 - t0
    speed = int(delta / t_delta * number_of_items / 1000)
    print('kupds/sec:', speed, 'total:', stats[0], 'len:', len(stats))
    last = stats[0]

    t0 = time.perf_counter()
```

The appraoch is how you have described it. Each process has a local dict where it is mainly working on. Once in a while, each process sends a signal to an updater thread. This thread then updates a central UltraDict that is shared among all processes. As we already know there are many updates we use a full dump technique in UltraDict so all the updates are only written together in one go.

The result:
```
622
kupds/sec: 30833 total: 622 len: 50000
1432
kupds/sec: 40280 total: 1432 len: 50000
2170
kupds/sec: 36700 total: 2170 len: 50000
2844
kupds/sec: 33485 total: 2844 len: 50000
3636
kupds/sec: 39449 total: 3636 len: 50000
```

Note that these are kilo updates per second, so with 4 processes I achieve like 40 million updates per second. With one process it's around 10 million updates. I do run this on a Lenovo X1 with an Intel Core i7 CPU. This means for 50k updates, it takes only 1.25 ms.

**Comment by rojamit** [comment]
@ronny-rentner thats really fast! i'll try it asap

**Comment by ronny-rentner** [comment]
I am closing this issue due to inactivity. Feel free to reopen if the problem persists.
